ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "extraTime" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "pkTeam1Goals" INTEGER;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "pkTeam2Goals" INTEGER;
